# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-10-07T11:50:15+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import User, Optional
from app.service import service

router = APIRouter(tags=["User"])


@router.get("/users/{username}", response_model=User, tags=["User"])
def get_user_by_name(
    username: str,
    with_email: Optional[bool] = None,
    pretty_print: Optional[bool] = None,
) -> User:
    """
    Get user by user name
    """
    return service.get_user_by_name(username)


@router.put("/users/{username}", response_model=None, tags=["User"])
def update_user(
    username: str, pretty_print: Optional[bool] = None, body: User = ...
) -> None:
    """
    Updated user
    """
    service.add_user(username, pretty_print, body)
    return
