# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-10-07T11:50:15+00:00

from __future__ import annotations

from fastapi import APIRouter, Body

from ..dependencies import *

router = APIRouter(tags=["Echo"])


@router.post("/echo", response_model=str, tags=["Echo"])
def echo(body: str = Body(..., embed=True)) -> str:
    """
    Echo test
    """
    return body
