# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-10-07T11:50:15+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['Health'])


@router.get(
    '/health',
    response_model=HealthGetResponse,
    responses={'503': {'model': HealthGetResponse1}},
    tags=['Health'],
)
def health_check() -> Union[HealthGetResponse, HealthGetResponse1]:
    """
    Health check of the service
    """
    pass
